//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ARK.Website.EntityFramework.Main
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ArkDatabase : DbContext
    {
        public ArkDatabase()
            : base("name=ArkDatabase")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Medlem> Medlems { get; set; }
        public DbSet<Regnskabsmedlem> Regnskabsmedlems { get; set; }
        public DbSet<Rostatistik> Rostatistiks { get; set; }
        public DbSet<Begivenhed> Begivenheds { get; set; }
        public DbSet<BilledDbBilleder> BilledDbBilleders { get; set; }
        public DbSet<BilledDbKarakterer> BilledDbKarakterers { get; set; }
        public DbSet<BilledDbKategoriRelation> BilledDbKategoriRelations { get; set; }
        public DbSet<BilledDbKkategorier> BilledDbKkategoriers { get; set; }
        public DbSet<Mail> Mails { get; set; }
        public DbSet<MailStatistik> MailStatistiks { get; set; }
    }
}
