//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ARK.Website.EntityFramework.Main
{
    using System;
    using System.Collections.Generic;
    
    public partial class BaadKategori
    {
        public BaadKategori()
        {
            this.BaadTypes = new HashSet<BaadType>();
        }
    
        public int ID { get; set; }
        public string Navn { get; set; }
    
        public virtual ICollection<BaadType> BaadTypes { get; set; }
    }
}
