//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ARK.Website.EntityFramework.Main
{
    using System;
    using System.Collections.Generic;
    
    public partial class Baad
    {
        public Baad()
        {
            this.Turs = new HashSet<Tur>();
        }
    
        public int ID { get; set; }
        public int BaadTypeID { get; set; }
        public string Navn { get; set; }
        public int AntalPersoner { get; set; }
    
        public virtual BaadType BaadType { get; set; }
        public virtual ICollection<Tur> Turs { get; set; }
    }
}
