//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ARK.Website.EntityFramework.Main
{
    using System;
    using System.Collections.Generic;
    
    public partial class BaadType
    {
        public BaadType()
        {
            this.Baads = new HashSet<Baad>();
        }
    
        public int ID { get; set; }
        public int BaadKategoriID { get; set; }
        public string Navn { get; set; }
    
        public virtual ICollection<Baad> Baads { get; set; }
        public virtual BaadKategori BaadKategori { get; set; }
    }
}
