//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ARK.Website.EntityFramework.Main
{
    using System;
    using System.Collections.Generic;
    
    public partial class BilledDbKkategorier
    {
        public BilledDbKkategorier()
        {
            this.BilledDbKategoriRelations = new HashSet<BilledDbKategoriRelation>();
        }
    
        public int kategoriID { get; set; }
        public string kategoriTitel { get; set; }
        public Nullable<int> raekkeFoelge { get; set; }
        public int superKategoriID { get; set; }
    
        public virtual ICollection<BilledDbKategoriRelation> BilledDbKategoriRelations { get; set; }
    }
}
