//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ARK.Website.EntityFramework.Main
{
    using System;
    using System.Collections.Generic;
    
    public partial class BilledDbKarakterer
    {
        public BilledDbKarakterer()
        {
            this.BilledDbBilleders = new HashSet<BilledDbBilleder>();
        }
    
        public int karakter { get; set; }
        public string titel { get; set; }
        public Nullable<int> raekkeFoelge { get; set; }
    
        public virtual ICollection<BilledDbBilleder> BilledDbBilleders { get; set; }
    }
}
