//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ARK.Website.EntityFramework.Main
{
    using System;
    using System.Collections.Generic;
    
    public partial class BilledDbBilleder
    {
        public BilledDbBilleder()
        {
            this.BilledDbKategoriRelations = new HashSet<BilledDbKategoriRelation>();
        }
    
        public int illustrationID { get; set; }
        public string filextension { get; set; }
        public string navn { get; set; }
        public string beskrivelse { get; set; }
        public Nullable<int> hojde { get; set; }
        public Nullable<int> bredde { get; set; }
        public string fotograf { get; set; }
        public string personer { get; set; }
        public Nullable<System.DateTime> dato { get; set; }
        public int karakter { get; set; }
        public string notat { get; set; }
        public string sted { get; set; }
        public Nullable<int> hits { get; set; }
        public Nullable<int> internHits { get; set; }
        public string originaltFilNavn { get; set; }
    
        public virtual ICollection<BilledDbKategoriRelation> BilledDbKategoriRelations { get; set; }
        public virtual BilledDbKarakterer BilledDbKarakterer { get; set; }
    }
}
