//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ARK.Website.EntityFramework.Main
{
    using System;
    using System.Collections.Generic;
    
    public partial class MailStatistik
    {
        public int ID { get; set; }
        public int ArkID { get; set; }
        public int Handling { get; set; }
        public int Mail_ID { get; set; }
    
        public virtual Mail Mail { get; set; }
    }
}
