//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ARK.Website.EntityFramework.Main
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tur
    {
        public Tur()
        {
            this.Turdeltagers = new HashSet<Turdeltager>();
        }
    
        public int ID { get; set; }
        public int BaadID { get; set; }
        public int AntalKilometer { get; set; }
        public System.DateTime StartTidspunkt { get; set; }
    
        public virtual Baad Baad { get; set; }
        public virtual ICollection<Turdeltager> Turdeltagers { get; set; }
    }
}
