//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ARK.Website.EntityFramework.Main
{
    using System;
    using System.Collections.Generic;
    
    public partial class Turdeltager
    {
        public int ID { get; set; }
        public int MedlemID { get; set; }
        public int TurID { get; set; }
    
        public virtual Medlem Medlem { get; set; }
        public virtual Tur Tur { get; set; }
    }
}
